name: Deployment Pipeline 

on:
  push:
      branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps: 
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'
          